//
//  MusicLibrary.swift
//  Minigolf
//
//  Generated by Tools/import_music.py from Tools/music_sources.json.
//  Do not edit by hand — edit the manifest and re-run the importer.
//

import Foundation

/// Everyone whose music is in the game — not only those the licence obliges us
/// to name. CC0 asks for nothing; putting the author in anyway costs a line and
/// is the difference between a credits screen and a disclaimer.
enum MusicCredit {
    static let authors = [
        "Joth",
        "Matthew Pablo",
        "Zane Little"
    ]

    /// The authors as one phrase, for a sentence rather than a list. Joined
    /// here rather than in the generator because the conjunction is a different
    /// word in each language the game speaks, and a generated string would be
    /// English inside a Czech sentence.
    static var authorList: String { authors.formatted(.list(type: .and)) }
}

/// One track, named. CC-BY wants the title of the work and not only who wrote
/// it, so the credits screen lists these rather than summarising them.
struct MusicWork: Identifiable, Hashable {
    let title: String
    let author: String
    let licence: String
    let link: String

    var id: String { title + author }
    var url: URL { URL(string: link) ?? URL(string: "https://opengameart.org/")! }

    static let all: [MusicWork] = [
        MusicWork(title: "A Cloudy Morning (Jazz)", author: "Matthew Pablo", licence: "CC-BY 3.0", link: "https://opengameart.org/content/a-cloudy-morning-jazz"),
        MusicWork(title: "Bossa Nova", author: "Joth", licence: "CC0", link: "https://opengameart.org/content/bossa-nova"),
        MusicWork(title: "Trouble Makers (Cool/Riff-Jazz)", author: "Matthew Pablo", licence: "CC-BY 3.0", link: "https://opengameart.org/content/trouble-makers-coolriff-jazz"),
        MusicWork(title: "Pleasant Creek", author: "Matthew Pablo", licence: "CC-BY 3.0", link: "https://opengameart.org/content/pleasant-creek"),
        MusicWork(title: "Apple Cider", author: "Zane Little", licence: "CC0", link: "https://opengameart.org/content/apple-cider"),
        MusicWork(title: "Salt Marsh Birds - Cute/Playful", author: "Matthew Pablo", licence: "CC-BY 3.0", link: "https://opengameart.org/content/salt-marsh-birds-cuteplayful"),
        MusicWork(title: "Miniature Saloon", author: "Zane Little", licence: "CC0", link: "https://opengameart.org/content/miniature-saloon"),
        MusicWork(title: "Wasteland Overdrive", author: "Matthew Pablo", licence: "CC-BY 3.0", link: "https://opengameart.org/content/wasteland-overdrive"),
        MusicWork(title: "Desolate", author: "Matthew Pablo", licence: "CC-BY 3.0", link: "https://opengameart.org/content/desolate"),
        MusicWork(title: "Woodland Fantasy", author: "Matthew Pablo", licence: "CC-BY 3.0", link: "https://opengameart.org/content/woodland-fantasy"),
        MusicWork(title: "Curious Critters", author: "Matthew Pablo", licence: "CC-BY 3.0", link: "https://opengameart.org/content/curious-critters"),
        MusicWork(title: "Glizzy Elf Forest [RPG MUSIC PACK]", author: "Zane Little", licence: "CC0", link: "https://opengameart.org/content/glizzy-elf-forest-rpg-music-pack"),
        MusicWork(title: "Snowland Town", author: "Matthew Pablo", licence: "CC-BY 3.0", link: "https://opengameart.org/content/snowland-town"),
        MusicWork(title: "Mirror Lake", author: "Joth", licence: "CC0", link: "https://opengameart.org/content/mirror-lake"),
        MusicWork(title: "The Frigid Seas", author: "Joth", licence: "CC0", link: "https://opengameart.org/content/the-frigid-seas"),
        MusicWork(title: "Sideways City", author: "Zane Little", licence: "CC0", link: "https://opengameart.org/content/sideways-city"),
        MusicWork(title: "Midnight Cruiser", author: "Zane Little", licence: "CC0", link: "https://opengameart.org/content/midnight-cruiser"),
        MusicWork(title: "Poker Night", author: "Zane Little", licence: "CC0", link: "https://opengameart.org/content/poker-night"),
        MusicWork(title: "Space Dimensions (Techno Version)", author: "Matthew Pablo", licence: "CC-BY 3.0", link: "https://opengameart.org/content/space-dimensions-techno-version"),
        MusicWork(title: "Shake and Bake", author: "Matthew Pablo", licence: "CC-BY 3.0", link: "https://opengameart.org/content/shake-and-bake"),
        MusicWork(title: "Rhythm Factory", author: "Zane Little", licence: "CC0", link: "https://opengameart.org/content/rhythm-factory"),
        MusicWork(title: "Thrust Sequence", author: "Matthew Pablo", licence: "CC-BY 3.0", link: "https://opengameart.org/content/thrust-sequence"),
        MusicWork(title: "Insect Factory (Wii-style music)", author: "Zane Little", licence: "CC0", link: "https://opengameart.org/content/insect-factory-wii-style-music"),
        MusicWork(title: "Toy Soldiers", author: "Zane Little", licence: "CC0", link: "https://opengameart.org/content/toy-soldiers"),
        MusicWork(title: "Enchanted Festival", author: "Matthew Pablo", licence: "CC-BY 3.0", link: "https://opengameart.org/content/enchanted-festival"),
        MusicWork(title: "Old Tricks", author: "Zane Little", licence: "CC0", link: "https://opengameart.org/content/old-tricks"),
        MusicWork(title: "Ireland's Coast (Game Edition)", author: "Matthew Pablo", licence: "CC-BY 3.0", link: "https://opengameart.org/content/irelands-coast-game-edition"),
        MusicWork(title: "Eye of the Storm", author: "Joth", licence: "CC0", link: "https://opengameart.org/content/eye-of-the-storm"),
        MusicWork(title: "Empty Stretch", author: "Zane Little", licence: "CC0", link: "https://opengameart.org/content/empty-stretch"),
        MusicWork(title: "Space Sprinkles", author: "Matthew Pablo", licence: "CC-BY 3.0", link: "https://opengameart.org/content/space-sprinkles"),
        MusicWork(title: "Interstellar Fleet 1", author: "Zane Little", licence: "CC0", link: "https://opengameart.org/content/interstellar-fleet-1"),
        MusicWork(title: "Space Dimensions (8bit/Retro Version)", author: "Matthew Pablo", licence: "CC-BY 3.0", link: "https://opengameart.org/content/space-dimensions-8bitretro-version")
    ]

    /// Grouped by author, each group in the order the manifest lists them.
    static var byAuthor: [(author: String, works: [MusicWork])] {
        var order: [String] = []
        var groups: [String: [MusicWork]] = [:]
        for work in all {
            if groups[work.author] == nil { order.append(work.author) }
            groups[work.author, default: []].append(work)
        }
        return order.map { ($0, groups[$0] ?? []) }
    }
}

extension MusicTrack {
    /// The resource names for this world, in manifest order.
    ///
    /// A world is a playlist rather than a single loop: one track of forty
    /// seconds gets heard six times while somebody lines up a putt, and by the
    /// fourth the melody is an irritation. `MusicPlayer` plays these once each
    /// in a shuffled order, crossfading one into the next.
    static let playlists: [MusicTrack: [String]] = [
        .menu: ["menu-1", "menu-2", "menu-3"],
        .garden: ["garden-1", "garden-2", "garden-3"],
        .desert: ["desert-1", "desert-2", "desert-3"],
        .jungle: ["jungle-1", "jungle-2", "jungle-3"],
        .ice: ["ice-1", "ice-2", "ice-3"],
        .neon: ["neon-1", "neon-2", "neon-3", "neon-4"],
        .volcano: ["volcano-1", "volcano-2", "volcano-3"],
        .clockwork: ["clockwork-1", "clockwork-2", "clockwork-3", "clockwork-4"],
        .storm: ["storm-1", "storm-2", "storm-3"],
        .cosmos: ["cosmos-1", "cosmos-2", "cosmos-3"]
    ]

    var resources: [String] { Self.playlists[self] ?? [] }
}
